language: node_js
sudo: false
node_js:
- 0.12
services:
- mongodb
- redis-server
addons:
  apt:
    packages:
    - graphicsmagick
    - ffmpeg
    - optipng
script:
- deploy/ci/travis.sh
env:
  global:
    - secure: he13bEicdzpoLGeoj+xaU2kIkKsw1/m+Ejcm5YanhGicECrCWVvFOu0O7vGHPDDj3s/xnTgBhhUPzIS3SdcIVqfTS+nP+CJNtzOm4zOdPvmfbfCvuIukLmCLtADrrz2HUxO1en1vfpH1trkUP5gwdo4vAGli7hOD4MsncRYaYio=
    - BUILDER="Travis CI"
