language: node_js
node_js:
- '0.10'
services:
- mongodb
- redis-server
script:
- deploy/ci/travis.sh
env:
  global:
    - secure: he13bEicdzpoLGeoj+xaU2kIkKsw1/m+Ejcm5YanhGicECrCWVvFOu0O7vGHPDDj3s/xnTgBhhUPzIS3SdcIVqfTS+nP+CJNtzOm4zOdPvmfbfCvuIukLmCLtADrrz2HUxO1en1vfpH1trkUP5gwdo4vAGli7hOD4MsncRYaYio=
    - BUILDER="Travis CI"
