language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphicsmagick pngquant optipng
before_script:
  - npm install -g grunt-cli
  - grunt build
